app/models.py
from . import login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from . import db, login_manager

class User(UserMixin, db.Model): 
    __tablename__ = 'users' 
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    task = db.relationship("Task")

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self): 
        return '<User %r>' % self.username

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class Task(db.Model):
    __tablename__ = 'tasks'
    id = db.Column(db.Integer, primary_key=True)
    priority = db.Column(db.Integer)
    text = db.Column(db.String)
    done = db.Column(db.Boolean)
    created_date = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
 

app/main/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import Required


class NameForm(Form):
    name = StringField('What is your name?', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config

bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    if not app.debug and not app.testing and not app.config['SSL_DISABLE']:
        from flask_sslify import SSLify
        sslify = SSLify(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from datetime import datetime

from flask import flash, render_template, session, redirect, url_for, current_app, request, jsonify
from datatables import ColumnDT, DataTables
from .. import db
from ..models import User, Task
from . import main
from .forms import NameForm

@main.route('/', methods=['GET', 'POST'])
def index():
    return render_template('index.html')

@main.route('/tasks/<username>', methods=['GET', 'POST'])
def tasks(username):
    return render_template('tasks.html', name=username)

@main.route('/data')
def data():
    """Return server side data."""
    # defining columns
    columns = []
    columns.append(ColumnDT('id'))
    columns.append(ColumnDT('priority'))
    columns.append(ColumnDT('text'))
    columns.append(ColumnDT('created_date'))

    # defining the initial query depending on your purpose
    query = db.session.query(User).join(Task)

    # instantiating a DataTable for the query and table needed
    rowTable = DataTables(request.args, User, query, columns)

    # returns what is needed by DataTable
    return jsonify(rowTable.output_result())

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Moneypenny{% endblock %}

{% block head %} 
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename = 'favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Moneypenny</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="{{ url_for('main.tasks', username=current_user.username) }}">Task List</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  {% for message in get_flashed_messages() %}
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
  </div>
  {% endfor %}
  
  {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Moneypenny{% endblock %}

{% block page_content %}
<div class="page-header">
  <h1>Hello, 
    {% if current_user.is_authenticated %}
        {{ current_user.username }}
    {% else %}
        Stranger
    {% endif %}
  </h1>
{% endblock %}

app/templates/tasks.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
  <!-- BEGIN GLOBAL MANDATORY STYLES -->
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
  <link href="{{ url_for('static', filename='font-awesome.min.css') }}" rel="stylesheet" type="text/css"/>
  <link href="{{ url_for('static', filename='simple-line-icons.min.css') }}" rel="stylesheet" type="text/css"/>
  <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet" type="text/css"/>
  <link href="{{ url_for('static', filename='uniform.default.css') }}" rel="stylesheet" type="text/css"/>
  <!-- END GLOBAL MANDATORY STYLES -->
  <!-- BEGIN PAGE LEVEL STYLES -->
  <link href="{{ url_for('static', filename='select2.css') }}" rel="stylesheet" type="text/css"/>
  <link href="{{ url_for('static', filename='dataTables.bootstrap.css') }}" rel="stylesheet" type="text/css"/>
  <!-- END PAGE LEVEL STYLES -->
  <!-- BEGIN THEME STYLES -->
  <link href="{{ url_for('static', filename='style-conquer.css') }}" rel="stylesheet" type="text/css"/>
  <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet" type="text/css"/>
  <link href="{{ url_for('static', filename='style-responsive.css') }}" rel="stylesheet" type="text/css"/>
  <link href="{{ url_for('static', filename='plugins.css') }}" rel="stylesheet" type="text/css"/>
  <link href="{{ url_for('static', filename='default.css') }}" rel="stylesheet" type="text/css" id="style_color"/>
  <link href="{{ url_for('static', filename='custom.css') }}" rel="stylesheet" type="text/css"/>
  <!-- END THEME STYLES -->
{% endblock %}

{% block page_content %}
  <div class="clearfix">
  </div>
  <!-- BEGIN CONTAINER -->
  <div class="page-container">
      <!-- BEGIN CONTENT -->
      <div class="page-content-wrapper">
          <div class="page-content">
              <!-- BEGIN PAGE CONTENT-->
              <div class="row">
                  <div class="col-md-12">
                      <!-- BEGIN EXAMPLE TABLE PORTLET-->
                      <div class="portlet">
                          <div class="portlet-title">
                              <div class="caption">
                                  <i class="fa fa-edit"></i>Editable Table
                              </div>
                              <div class="tools">
                                  <a href="javascript:;" class="collapse">
                                  </a>
                                  <a href="#portlet-config" data-toggle="modal" class="config">
                                  </a>
                                  <a href="javascript:;" class="reload">
                                  </a>
                                  <a href="javascript:;" class="remove">
                                  </a>
                              </div>
                          </div>
                          <div class="portlet-body">
                              <div class="table-toolbar">
                                  <div class="row">
                                      <div class="col-md-6">
                                          <div class="btn-group">
                                              <button id="sample_editable_1_new" class="btn btn-success">
                                              Add New <i class="fa fa-plus"></i>
                                              </button>
                                          </div>
                                      </div>
                                      <div class="col-md-6">
                                          <div class="btn-group pull-right">
                                              <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
                                              </button>
                                              <ul class="dropdown-menu pull-right">
                                                  <li>
                                                      <a href="#">
                                                      Print </a>
                                                  </li>
                                                  <li>
                                                      <a href="#">
                                                      Save as PDF </a>
                                                  </li>
                                                  <li>
                                                      <a href="#">
                                                      Email </a>
                                                  </li>
                                              </ul>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <table class="table table-striped table-hover table-bordered" id="sample_editable_1">
                              <thead>
                              <tr>
                                  <th>
                                       ID
                                  </th>
                                  <th>
                                       Priority
                                  </th>
                                  <th>
                                       Task
                                  </th>
                                  <th>
                                       Created
                                  </th>
                                  <th>
                                       Action
                                  </th>
                              </tr>
                              </thead>
                              <tbody>
                              <tr>
                                  <td>
                                       1
                                  </td>
                                  <td>
                                       High
                                  </td>
                                  <td>
                                       Buy Pancake Mix
                                  </td>
                                  <td>
                                       2016-05-31
                                  </td>
                                  <td>
                                      <a class="edit" href="javascript:;">
                                      Complete </a> |
                                      <a class="delete" href="javascript:;">
                                      Delete </a>
                                  </td>
                              </tr>
                              </tbody>
                              </table>
                          </div>
                      </div>
                      <!-- END EXAMPLE TABLE PORTLET-->
                  </div>
              </div>
              <!-- END PAGE CONTENT -->
          </div>
      </div>
      <!-- END CONTENT -->
  </div>
  <!-- END CONTAINER -->
{% endblock %}

{% block scripts %}
  <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
  <!-- BEGIN CORE PLUGINS -->
  <script src="{{ url_for('static', filename='jquery-1.11.0.min.js') }}" type="text/javascript"></script>
  <script src="{{ url_for('static', filename='jquery-migrate-1.2.1.min.js') }}" type="text/javascript"></script>
  <!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
  <script src="{{ url_for('static', filename='jquery-ui-1.10.3.custom.min.js') }}" type="text/javascript" ></script>
  <script src="{{ url_for('static', filename='bootstrap.min.js') }}" type="text/javascript"></script>
  <script src="{{ url_for('static', filename='bootstrap-hover-dropdown.min.js') }}" type="text/javascript"></script>
  <script src="{{ url_for('static', filename='jquery.slimscroll.min.js') }}" type="text/javascript"></script>
  <script src="{{ url_for('static', filename='blockui.min.js') }}" type="text/javascript"></script>
  <script src="{{ url_for('static', filename='jquery.uniform.min.js') }}" type="text/javascript"></script>
  <!-- END CORE PLUGINS -->
  <!-- BEGIN PAGE LEVEL PLUGINS -->
  <script src="{{ url_for('static', filename='select2.min.js') }}" type="text/javascript" ></script>
  <script src="{{ url_for('static', filename='jquery.dataTables.min.js') }}" type="text/javascript"></script>
  <script src="{{ url_for('static', filename='dataTables.bootstrap.js') }}" type="text/javascript"></script>
  <!-- END PAGE LEVEL PLUGINS -->
  <!-- BEGIN PAGE LEVEL SCRIPTS -->
  <script src="{{ url_for('static', filename='app.js') }}" type="text/javascript"></script>
  <script src="{{ url_for('static', filename='table-editable.js') }}" type="text/javascript"></script>
  <script>
  jQuery(document).ready(function() {       
     App.init();
     TableEditable.init();
  });
  </script>
<!-- These are the scripts provided by sqlalchemy-datatables -->
<!--
  <script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
      var table = $('sample_editable_1').DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": "{{ url_for('main.data') }}"
      });
    });
    console.log(table)
  </script>
-->
{% endblock %}